#if !canImport(ObjectiveC)
import XCTest

extension XPathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XPathTests = [
        ("testSimpleXPath", testSimpleXPath),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XPathTests.__allTests__XPathTests),
    ]
}
#endif
